# Generated by Django 2.0.2 on 2018-02-26 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversion', '0002_auto_20180224_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Converter',
            new_name='ConverterHistory',
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'ordering': ['name']},
        ),
    ]
